module.exports =  [
  {
    id  : 101,
    name  : "Hilden Brewery",
    established  : 1981,
    street_address  : "Hilden House Grand Street, Hilden,",
    town  : "Lisburn",
    county  : "Antrim",
    country  : "Northern Ireland",
    postcode  : "BT27 4TY",
    website  : "http://www.hildenbrewery.com/",
    email  : "info@hildenbrewery.co.uk",
    telephone  : "028 9266 0800",
    facebook  : "https://www.facebook.com/HildenBrewery/",
    twitter  : "https://twitter.com/hildenbrewery",
    instagram  : "https://www.instagram.com/hildenbrewingco/",
    trading_as  : "Hilden Brewery Limited",
    company_number  : "NI638918",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI638918"
  },
  {
    id  : 102,
    name  : "Whitewater Brewing",
    established  : 1996,
    street_address  : "Lakeside Brae",
    town  : "Castlewellan",
    county  : "Down",
    country  : "Northern Ireland",
    postcode  : "BT31 9RH",
    website  : "https://whitewaterbrewery.com/",
    email  : "info@whitewaterbrewery.com",
    telephone  : "028 437 78900",
    facebook  : "https://www.facebook.com/WhitewaterBeer/",
    twitter  : "https://twitter.com/Whitewaterbeer",
    instagram  : "https://www.instagram.com/whitewaterbeer/",
    trading_as  : "WHITEWATER BREWING CO. LTD",
    company_number  : "NI041141",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI041141"
  },
  {
    id  : 103,
    name  : "InishMacSaint",
    established  : 2010,
    street_address  : "75-77 Main Street",
    town  : "Derrygonnelly",
    county  : "Fermanagh",
    country  : "Northern Ireland",
    postcode  : "BT93 6HW",
    website  : "http://inishmacsaint.beer/",
    email  : "fermanaghbeercompany@gmail.com",
    telephone  : "028 68641254",
    facebook  : "https://www.facebook.com/inishmacsaint/",
    twitter  : "https://twitter.com/InishMacSaintBC",
    instagram  : "https://www.instagram.com/inishmacsaint/",
    trading_as  : "FERMANAGH BEER COMPANY LIMITED",
    company_number  : "NI640631",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI640631"
  },
  {
    id  : 104,
    name  : "Ards Brewing Co",
    established  : 2011,
    street_address  : "34b Carrowdore Road, Greyabbey",
    town  : "Newtownards",
    county  : "Down",
    country  : "Northern Ireland",
    postcode  : "BT22 2LX",
    website  : "",
    email  : "ardsbrewing@blackwood34.plus.com",
    telephone  : "075 15558406",
    facebook  : "https://www.facebook.com/ArdsBrewing/",
    twitter  : "https://twitter.com/ArdsBrewing",
    instagram  : "None at present",
    trading_as  : "ARDS BREWING COMPANY LTD",
    company_number  : "NI606545",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI606545"
  },
  {
    id  : 105,
    name  : "Farmageddon Brewery",
    established  : 2014,
    street_address  : "25 Ballykeigle Road, Comber",
    town  : "Newtownards",
    county  : "Down",
    country  : "Northern Ireland",
    postcode  : "BT23 5SD",
    website  : "http://www.farmageddonbrewing.com/",
    email  : "info@farmageddonbrewing.com",
    telephone  : "079 66809481",
    facebook  : "https://www.facebook.com/FarmageddonBeer/",
    twitter  : "https://twitter.com/FarmageddonBeer",
    instagram  : "None at present",
    trading_as  : "FARMAGEDDON BREWING LIMITED",
    company_number  : "NI649790",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI649790"
  },
  {
    id  : 106,
    name  : "Hercules Brewing/ Yardsman",
    established  : 2014,
    street_address  : "Hercules Court, 5 Harbour Court, Heron Road",
    town  : "Belfast",
    county  : "Antrim",
    country  : "Northern Ireland",
    postcode  : "BT3 9HB",
    website  : "http://www.yardsmanlager.com/",
    email  : "niall@herculesbrewery.com",
    telephone  : "028 9073 2206",
    facebook  : "https://www.facebook.com/yardsmanlager",
    twitter  : "https://twitter.com/YardsmanLager",
    instagram  : "https://www.instagram.com/yardsmanlager/",
    trading_as  : "HERCULES BREWING & CO. LIMITED",
    company_number  : "NI615817",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI615817"
  },
  {
    id  : 107,
    name  : "Hillstown",
    established  : 2014,
    street_address  : "128 Glebe Road",
    town  : "Randalstown",
    county  : "Antrim",
    country  : "Northern Ireland",
    postcode  : "BT41 3DT",
    website  : "https://www.hillstownbrewery.com/",
    email  : "info@hillstownbrewery.com",
    telephone  : "028 9447 8662",
    facebook  : "https://www.facebook.com/hillstownbrewery/",
    twitter  : "https://twitter.com/hillstownbeer",
    instagram  : "https://www.instagram.com/hillstownbrewery/",
    trading_as  : "HFBC LTD",
    company_number  : "NI628141",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI628141"
  },
  {
    id  : 108,
    name  : "Walled City Brewery",
    established  : 2014,
    street_address  : "70 Ebrington Square & Parade Ground",
    town  : "Derry/Londonderry",
    county  : "Derry/Londonderry",
    country  : "Northern Ireland",
    postcode  : "BT47 6FA",
    website  : "http://www.walledcitybrewery.com/",
    email  : "info@walledcitybrewery.com",
    telephone  : "028 71343336",
    facebook  : "https://www.facebook.com/walledcitybrewery/",
    twitter  : "https://twitter.com/walledcitybrew",
    instagram  : "https://www.instagram.com/walledcitybrewery/",
    trading_as  : "Legenderry Brewing Company Limited",
    company_number  : "NI624606",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI624606"
  },
  {
    id  : 109,
    name  : "Northbound Brewing",
    established  : 2014,
    street_address  : "6 McLean Road",
    town  : "Derry/Londonderry",
    county  : "Derry/Londonderry",
    country  : "Northern Ireland",
    postcode  : "BT47 3XX",
    website  : "http://www.northboundbrewery.com/",
    email  : "cheers@northboundbrewery.com",
    telephone  : "075 12198686",
    facebook  : "https://www.facebook.com/Northboundbrewery",
    twitter  : "https://twitter.com/northboundmbrew",
    instagram  : "https://www.instagram.com/northboundbrewery/",
    trading_as  : "Northbound Brewery Limited",
    company_number  : "NI618957",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI618957"
  },
  {
    id  : 110,
    name  : "Knockout Brewing",
    established  : 2015,
    street_address  : "10-11 Alanbrooke Park Ind. Estate",
    town  : "Belfast",
    county  : "Antrim",
    country  : "Northern Ireland",
    postcode  : "BT6 9HB",
    website  : "http://www.knockoutbrewing.com/",
    email  : "",
    telephone  : "074 60775104",
    facebook  : "https://www.facebook.com/KnockoutBrewingBelfast",
    twitter  : "Https://twitter.com/knockoutbrewing",
    instagram  : "None at present",
    trading_as  : "",
    company_number  : "",
    companies_house_url  : ""
  },
  {
    id  : 111,
    name  : "Boundary Co-Operative Brewing",
    established  : 2015,
    street_address  : "A5 Portview Trade Centre, 310 Newtownards Rd",
    town  : "Belfast",
    county  : "Antrim",
    country  : "Northern Ireland",
    postcode  : "BT4 1HE",
    website  : "https://boundarybrewing.coop/",
    email  : "info@boundarybrewing.coop",
    telephone  : "",
    facebook  : "https://www.facebook.com/boundarybrewingcoop/",
    twitter  : "https://twitter.com/boundarybrewing",
    instagram  : "https://www.instagram.com/boundarybrewing",
    trading_as  : "BOUNDARY BREWING COOPERATIVE LIMITED",
    company_number  : "NP000409",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NP000409"
  },
  {
    id  : 112,
    name  : "Lacada Co-Operative Brewing",
    established  : 2015,
    street_address  : "7A Victoria St",
    town  : "Portrush",
    county  : "Antrim",
    country  : "Northern Ireland",
    postcode  : "BT56 8DL",
    website  : "http://www.lacadabrewery.com/",
    email  : "info@lacadabrewery.com",
    telephone  : "028 7082 5684",
    facebook  : "http://www.facebook.com/lacadabrewery",
    twitter  : "https://twitter.com/LacadaBrew",
    instagram  : "http://instagram.com/lacadabrewery",
    trading_as  : "LACADA BREWERY LIMITED",
    company_number  : "NP000412",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NP000412"
  },
  {
    id  : 113,
    name  : "Mourne Mountains",
    established  : 2015,
    street_address  : "Milltown East Industrial Estate, Upper Dromore Rd, Warrenpoint",
    town  : "Newry",
    county  : "Down",
    country  : "Northern Ireland",
    postcode  : "BT34 3PN",
    website  : "http://www.mournemountainsbrewery.com/",
    email  : "info@mournemountainsbrewery.com",
    telephone  : "028 4175 2299",
    facebook  : "https://www.facebook.com/MourneMountainsBrew",
    twitter  : "Https://twitter.com/MourneBrewery",
    instagram  : "https://www.instagram.com/mournemountainsbrewery/",
    trading_as  : "MOURNE MOUNTAINS BREWERY LIMITED",
    company_number  : "NI059426",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI059426"
  },
  {
    id  : 114,
    name  : "O'Connor Craft",
    established  : 2015,
    street_address  : "12 Lime Road, Greysteel",
    town  : "Derry/Londonderry",
    county  : "Derry/Londonderry",
    country  : "Northern Ireland",
    postcode  : "BT47 3EH",
    website  : "",
    email  : "",
    telephone  : "077 48004065",
    facebook  : "https://www.facebook.com/O-Connor-Craft-Beer-781479541895087/",
    twitter  : "",
    instagram  : "",
    trading_as  : "",
    company_number  : "",
    companies_house_url  : ""
  },
  {
    id  : 115,
    name  : "Black Mountain",
    established  : 2016,
    street_address  : "47 DERRIAGHY ROAD",
    town  : "Lisburn",
    county  : "Antrim",
    country  : "Northern Ireland",
    postcode  : "BT28 3SH",
    website  : "https://www.speckledhenlisburn.com/black-mountain-brewery/",
    email  : "speckledhenlisburn@gmail.com",
    telephone  : "028 9061 1113",
    facebook  : "https://m.facebook.com/speckledhenlisburn/",
    twitter  : "https://twitter.com/thespeckled_hen",
    instagram  : "http://instagram.com/thespeckled_hen",
    trading_as  : "BLACK MOUNTAIN BREWING COMPANY LTD",
    company_number  : "NI615476",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI615476"
  },
  {
    id  : 116,
    name  : "Bullhouse Brewing",
    established  : 2016,
    street_address  : "10 Greengraves Road",
    town  : "Newtownards",
    county  : "Down",
    country  : "Northern Ireland",
    postcode  : "BT23 5AG",
    website  : "http://bullhousebeer.co.uk",
    email  : "info@bullhousebeer.co.uk",
    telephone  : "075 62702525",
    facebook  : "https://www.facebook.com/bullhousebeer",
    twitter  : "https://twitter.com/bullhousebeer",
    instagram  : "https://www.instagram.com/bullhousebeer/",
    trading_as  : "BULLHOUSE BREWING COMPANY LIMITED",
    company_number  : "NI649422",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI649422"
  },
  {
    id  : 117,
    name  : "Heaney Farmhouse Brewing",
    established  : 2016,
    street_address  : "The Wood, Bellaghy",
    town  : "Belfast",
    county  : "Antrim",
    country  : "Northern Ireland",
    postcode  : "BT4 1HE",
    website  : "https://www.heaney.ie",
    email  : "hello@heaney.ie",
    telephone  : "077 61514287",
    facebook  : "https://www.facebook.com/Heaneybrewery/",
    twitter  : "https://twitter.com/HeaneyBrewery",
    instagram  : "http://instagram.com/heaneybrewery",
    trading_as  : "HEANEY BREWING COMPANY LIMITED",
    company_number  : "NI639121",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI639121"
  },
  {
    id  : 118,
    name  : "Beer Hut Brewing",
    established  : 2017,
    street_address  : "6 Riverside Park, Kilkeel",
    town  : "Newry",
    county  : "Down",
    country  : "Northern Ireland",
    postcode  : "BT34 4NA",
    website  : "https://www.beerhutbrewing.shop",
    email  : "sales@beerhutbrewing.shop",
    telephone  : "078 85566599",
    facebook  : "http://www.facebook.com/beerhutbrewing/",
    twitter  : "http://www.twitter.com/beerhutbrewing",
    instagram  : "https://www.instagram.com/beerhutbrewing/",
    trading_as  : "BEER HUT BREWING COMPANY LTD",
    company_number  : "NI643050",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI643050"
  },
  {
    id  : 119,
    name  : "MashDown Brewing",
    established  : 2018,
    street_address  : "58 Castlewellan Road",
    town  : "Banbridge",
    county  : "Down",
    country  : "Northern Ireland",
    postcode  : "BT32 3SF",
    website  : "http://www.mashdownbrewery.com/",
    email  : "chris@mashdownbrewery.com",
    telephone  : "078 66580077",
    facebook  : "https://www.facebook.com/mashdownbrewery/",
    twitter  : "https://twitter.com/mashdownbrewery",
    instagram  : "https://www.instagram.com/mashdownbrewery/",
    trading_as  : "MASHDOWN BREWERY LTD.",
    company_number  : "NI623631",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI623631"
  },
  {
    id  : 120,
    name  : "Baronscourt",
    established  : 2018,
    street_address  : "38 Baronscourt Road, Newtownstewart",
    town  : "Omagh",
    county  : "Tyrone",
    country  : "Northern Ireland",
    postcode  : "BT78 4EY",
    website  : "https://www.baronscourtbrewery.com",
    email  : "baronscourtbrewing.co@gmail.com",
    telephone  : "",
    facebook  : "https://www.facebook.com/baronscourtbrewing",
    twitter  : "https://twitter.com/baronscourtbrew",
    instagram  : "https://www.instagram.com/baronscourtbrewing.co/",
    trading_as  : "BARONSCOURT BREWING COMPANY LTD",
    company_number  : "NI650446",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI650446"
  },
  {
    id  : 121,
    name  : "Lecale",
    established  : 2018,
    street_address  : "5 High Street, Ardglass",
    town  : "Ardglass",
    county  : "Down",
    country  : "Northern Ireland",
    postcode  : "BT30 7TU",
    website  : "https://www.lecalebrewery.com",
    email  : "info@lecalebrewery.com",
    telephone  : "077 63142100",
    facebook  : "https://www.facebook.com/lecalebrewery",
    twitter  : "https://twitter.com/lecalebrewery",
    instagram  : "https://www.instagram.com/lecalebrewery/",
    trading_as  : "LECALE BREWING COMPANY LIMITED",
    company_number  : "NI643853",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI643853"
  },
  {
    id  : 122,
    name  : "McCrackens",
    established  : 2018,
    street_address  : "Derryall Road",
    town  : "Portadown",
    county  : "Armagh",
    country  : "Northern Ireland",
    postcode  : "BT62 1PL",
    website  : "https://www.mccrackensrealale.com",
    email  : "sales@mccrackensrealale.com",
    telephone  : "078 03045124",
    facebook  : "https://www.facebook.com/mccrackensrealale/",
    twitter  : "https://twitter.com/MccrackensAle",
    instagram  : "https://www.instagram.com/mccrackensrealale/",
    trading_as  : "",
    company_number  : "",
    companies_house_url  : ""
  },
  {
    id  : 123,
    name  : "Rough Brothers",
    established  : 2019,
    street_address  : "",
    town  : "Derry/Londonderry",
    county  : "Derry/Londonderry",
    country  : "Northern Ireland",
    postcode  : "",
    website  : "",
    email  : "",
    telephone  : "079 46638513",
    facebook  : "https://www.facebook.com/Rough-Brothers-Handmade-BEER-716098062081043/",
    twitter  : "",
    instagram  : "",
    trading_as  : "ROUGH BROTHERS BREWING LIMITED",
    company_number  : "NI656139",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI656139"
  },
  {
    id  : 124,
    name  : "Norn Iron Brew Co",
    established  : 2019,
    street_address  : "87 Priory Park, Derriaghy",
    town  : "Belfast",
    county  : "Antrim",
    country  : "Northern Ireland",
    postcode  : "BT10 0AG",
    website  : "",
    email  : "",
    telephone  : "",
    facebook  : "https://www.facebook.com/nornironbrewco/",
    twitter  : "https://twitter.com/nornironbrewco",
    instagram  : "https://www.instagram.com/nornironbrewcoltd/",
    trading_as  : "NORN IRON BREW COMPANY LIMITED",
    company_number  : "NI638864",
    companies_house_url  : "https://beta.companieshouse.gov.uk/company/NI638864"
  },
  {
    id  : 125,
    name  : "Modest Brewing",
    established  : 2019,
    street_address  : "10a My Lady's Mile",
    town  : "Holywood",
    county  : "Down",
    country  : "Northern Ireland",
    postcode  : "BT18 9EW",
    website  : "https://www.modestbeer.co.uk",
    email  : "",
    telephone  : "",
    facebook  : "https://www.facebook.com/modestbeer/",
    twitter  : "https://twitter.com/modestbeer",
    instagram  : "https://www.instagram.com/modestbeer/",
    trading_as  : "",
    company_number  : "",
    companies_house_url  : ""
  },
  {
    id  : 126,
    name  : "Twisted Kettle",
    established  : 2019,
    street_address  : "",
    town  : "Donaghadee",
    county  : "Down",
    country  : "Northern Ireland",
    postcode  : "",
    website  : "",
    email  : "",
    telephone  : "",
    facebook  : "https://www.facebook.com/twistedkettle/",
    twitter  : "https://twitter.com/twisted_kettle",
    instagram  : "https://www.instagram.com/twisted_kettle/",
    trading_as  : "",
    company_number  : "",
    companies_house_url  : ""
  }
]